/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --include-env=true` (hash: 869ac3b4ce0f52ba3b2e0bc70c49089e)
declare namespace Cloudflare {
  interface Env {
    MERCHANT_ADDRESS: `0x${string}`
    MERCHANT_PRIVATE_KEY: `0x${string}`
  }
}
interface Env extends Cloudflare.Env {}
