/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WalletconnectImport } from './routes/wallet_connect'

// Create/Update Routes

const WalletconnectRoute = WalletconnectImport.update({
  id: '/wallet_connect',
  path: '/wallet_connect',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet_connect': {
      id: '/wallet_connect'
      path: '/wallet_connect'
      fullPath: '/wallet_connect'
      preLoaderRoute: typeof WalletconnectImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/wallet_connect': typeof WalletconnectRoute
}

export interface FileRoutesByTo {
  '/wallet_connect': typeof WalletconnectRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/wallet_connect': typeof WalletconnectRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/wallet_connect'
  fileRoutesByTo: FileRoutesByTo
  to: '/wallet_connect'
  id: '__root__' | '/wallet_connect'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  WalletconnectRoute: typeof WalletconnectRoute
}

const rootRouteChildren: RootRouteChildren = {
  WalletconnectRoute: WalletconnectRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/wallet_connect"
      ]
    },
    "/wallet_connect": {
      "filePath": "wallet_connect.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
